cargo-features = ["panic-immediate-abort"]

[workspace]
resolver = "3"
members = ["iotd", "lib/aps-crypto", "lib/sx1278"]

[workspace.package]
edition = "2024"
version = "0.1.2"
authors = ["Stefano Fontana <s.fontana@apogeo.space>"]

[workspace.dependencies]
sx1278 = {path = "./lib/sx1278"}
aps-crypto = {path = "./lib/aps-crypto"}

[profile.release]
panic = "immediate-abort"
lto = true
opt-level = 3
codegen-units = 1
strip = "debuginfo"

[profile.dev]
opt-level = 1
panic = "immediate-abort"
debug = "full"

[profile.test]
opt-level = 3
debug = "full"
lto = true
