// extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn main() {

    // let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // cbindgen::Builder::new()
    //   .with_crate(crate_dir.as_str())
    //   .with_no_includes()
    //   .with_include_guard("__IOTD__RS_INTERFACE_H__")
    //   .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
    //   .with_language(cbindgen::Language::C)
    //   .with_style(cbindgen::Style::Type)
    //   .generate()
    //   .expect("Unable to generate bindings")
    //   .write_to_file(format!("{crate_dir}/../module/include/iotd/rs/provided.h").as_str());

    let bindings = bindgen::Builder::default()
        .header(format!("{}/module/include/iotd/rs/callbacks.h", env::var("TOPDIR").unwrap()))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .use_core()
        .generate()
        .expect("Unable to generate bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}