[unstable]
build-std = ["core", "alloc"]

[build]
rustflags = ["-C", "panic=abort", "-Z", "panic_abort_tests"]

[target.aarch64-unknown-none-gnu]
linker = "ld"

[target.arm-unknown-none-gnu]
linker = "ld"

[alias]
test_lib = "test --target=aarch64-unknown-linux-gnu -Zbuild-std=panic_abort,std"
