#ifndef __IOTD__RS__PROVIDED_H__
#define __IOTD__RS__PROVIDED_H__

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */



typedef enum {
  InternalLogLevelTrace = 0,
  InternalLogLevelDebug,
  InternalLogLevelInfo,
  InternalLogLevelNotice,
  InternalLogLevelWarning,
  InternalLogLevelError,
  InternalLogLevelAlert,
  InternalLogLevelEmerg,
} ShimLogLevel;

typedef struct {
  uint8_t spreading_factor;
  uint8_t coding_rate;
  uint8_t bandwidth;
  bool use_header;
  bool use_payload_crc;
  bool use_cad;
  bool use_ldro;
  uint16_t preamble_length;
  uint32_t xtal_freq;
  bool xtal_is_tcxo;
  uint32_t carrier_frequency;
  int16_t output_power;
  uint8_t pa_boost;
  uint16_t nation_id;
  uint32_t node_id;
  uint8_t node_key[32];
} IotdConfig;

extern void __internal_log_shim(ShimLogLevel level, const char *msg);

extern void panic(const char *fmt, ...);

void r_config_notify(void *ctx, const IotdConfig *new_conf);

int32_t r_dev_close(void *ctx);

int32_t r_dev_opened(void *ctx, bool _write);

void r_device_drop(void *ctx);

void *r_driver_init(void *ctx, bool polling, bool aps_proto, const IotdConfig *config);

int r_irq_notify(void *ctx);

int32_t r_receive(void *ctx, uint8_t *buf, size_t sz);

int32_t r_transmit(void *ctx, const uint8_t *payload, size_t sz);

#endif  /* __IOTD__RS__PROVIDED_H__ */
